CREATE DATABASE mc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mc;
CREATE TABLE rimc(
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
) ENGINE_innoDB;
