--tabla de tipo de usuarios
CREATE TABLE IF NOT EXISTS tipo_usuarios
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL UNIQUE

--tipo de planes
CREATE TABLE IF NOT EXISTS tipo_planes
id INT AUTO_INCREMENT PRIMARY KEY,
tipo_plan VARCHAR(100) NOT NULL
duracion_meses INT AUTO_INCREMENT PRIMARY KEY
id_pago INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--Pagos
CREATE TABLE IF NOT EXTIST pagos
id INT AUTO_INCREMENT PRIMARY KEY
tipo_de_pago VARCHAR(100) NOT NULL

--sugerencias
CREATE TABLE IF NOT EXISTS sugerencias
id INT AUTO_INCREMENT PRIMARY KEY
calificacion INT AUTO_INCREMENT PRIMARY KEY
comentario VARCHAR(100) NOT NULL
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA
tipo_sugerencia VARCHAR(100) NOT NULL

--gastos
CREATE TABLE IF NOT EXISTS gastos
id INT AUTO_INCREMENT PRIMARY KEY
valor INT AUTO_INCREMENT PRIMARY KEY
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--ingresos
CREATE TABLE IF NOT EXISTS ingresos
id INT AUTO_INCREMENT PRIMARY KEY
valor INT AUTO_INCREMENT PRIMARY KEY
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--tipo de sugerencias
CREATE TABLE IF NOT EXISTS tipo_sugerencia
id INT AUTO_INCREMENT PRIMARY KEY
nombre_tipo_sugerencia VARCHAR(100) NOT NULL

--categoria gastos
CREATE TABLE IF NOT EXISTS categoria_gastos
id INT AUTO_INCREMENT PRIMARY KEY
nombre VARCHAR(100) NOT NULL
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--categoria ingresos
CREATE TABLE IF NOT EXISTS categoria_ingresos
id INT AUTO_INCREMENT PRIMARY KEY
nombre VARCHAR(100) NOT NULL
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA
